// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

import (
	"github.com/google/wire"
	"io"
	"os"
)

// Injectors from injector.go:

func InitializedService(iSError bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(iSError)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

func InitializedDatabase() *DatabaseRepository {
	postgreSql := NewPostgreSql()
	mongoDB := NewMongoDB()
	databaseRepository := NewDatabaseRepository(postgreSql, mongoDB)
	return databaseRepository
}

func InitializedFooBar() *FooBar {
	barRepository := NewBarRepository()
	barService := NewBarService(barRepository)
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository)
	fooBar := NewFooBar(barService, fooService)
	return fooBar
}

func InitializedHelloService() *HelloService {
	sayHelloImpln := NewSayHelloImpln()
	helloService := NewHelloService(sayHelloImpln)
	return helloService
}

func InitializedFoo_Bar() *Foo_Bar {
	bar := NewBar()
	foo := NewFoo()
	foo_Bar := &Foo_Bar{
		Bar: bar,
		Foo: foo,
	}
	return foo_Bar
}z

func InitializedFooBarUsingValue() *Foo_Bar {
	foo := _wireFooValue
	bar := _wireBarValue
	foo_Bar := &Foo_Bar{
		Foo: foo,
		Bar: bar,
	}
	return foo_Bar
}

var (
	_wireFooValue = fooValue
	_wireBarValue = barValue
)

func InitializedReader() io.Reader {
	reader := _wireFileValue
	return reader
}

var (
	_wireFileValue = os.Stdin
)

func InitializedConfiguration() *Configuration {
	aplication := NewAplication()
	configuration := aplication.Configuration
	return configuration
}

// injector.go:

var setFoo = wire.NewSet(NewFooRepository, NewFooService)

var setBar = wire.NewSet(NewBarRepository, NewBarService)

var setHello = wire.NewSet(NewSayHelloImpln, wire.Bind(new(SayHello), new(*SayHelloImpln)))

var fooValue = &Foo{}

var barValue = &Bar{}
