// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

// Injectors from injector.go:

func InitializedService(iSError bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(iSError)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

func InitializedDatabase() *DatabaseRepository {
	postgreSql := NewPostgreSql()
	mongoDB := NewMongoDB()
	databaseRepository := NewDatabaseRepository(postgreSql, mongoDB)
	return databaseRepository
}
